actor_learning_rate: 1e-4
ae_hypers:
  actor_learning_rate: 1e-4
  autoencoder: None
  autoencoder_lr: 0.001
  autoencoder_num_epochs: 15
  autoencoder_saving_period: 10
  critic_learning_rate: 1e-3
  hidden_size: 16
autoencoder: None
autoencoder_lr: 0.001
autoencoder_num_epochs: 15
autoencoder_saving_period: 10
context_dim: 5
critic_learning_rate: 1e-3
device: mps
domain: sepsis
drop_smaller_than_minibatch: true
folder_location: /data
folder_name: ..
hidden_size: 16
minibatch_size: 16
num_actions: 2
perception_neg_traj_ratio: NA
random_seed: 1234
resume: false
rng: 1234
sided_Q: negative
state_dim: 33
storage_path: ~/Documents/ETHZ/MA2/Research in Data Science/RL-for-sepsis
test_data_file: test_set_tuples
train_data_file: train_set_tuples
validation_data_file: val_set_tuples
