random_seed: 1234 # updated by run scripts
folder_location: '/data'
folder_name: '/combined' # updated by run scripts
resume: False
minibatch_size: 16
drop_smaller_than_minibatch: True
sided_Q: 'negative'  #Can be 'positive' or 'negative'
perception_neg_traj_ratio: 'NA'

state_dim: 33                      
num_actions: 2
context_dim: 5                    


# update these manually
storage_path: '~/Documents/ETHZ/MA2/Research in Data Science/RL-for-sepsis'

train_data_file: '../data/train_set_tuples'
validation_data_file: '../data/val_set_tuples'
test_data_file: '../data/test_set_tuples'
